### ISSUE TITLE
Error after running script on odoo

### ISSUE THREAD

**Issue by obsess** [aschenkels-ictstudio/odoo-install-scripts#6]
I tried doing a manual install and had no issues and was excited to try this script. So i started with a fresh 14.04 and ran the script. Everything seemed to go great and access the site:8069. While trying to create the DB (in the web browser session) I get the following error. I think something may need to be tweaked but I am not familiar enough with the product or script. Running the v8 script.

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 476, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 495, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 312, in _call_function
    return self.endpoint(_args, **kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 685, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 360, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 686, in create
    params['create_admin_pwd'])
  File "/opt/odoo/odoo-server/openerp/http.py", line 759, in proxy_method
    result = dispatch_rpc(self.service_name, method, args)
  File "/opt/odoo/odoo-server/openerp/http.py", line 93, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo/odoo-server/openerp/service/db.py", line 62, in dispatch
    security.check_super(passwd)
  File "/opt/odoo/odoo-server/openerp/service/security.py", line 33, in check_super
    raise openerp.exceptions.AccessDenied()
AccessDenied: Access denied.

I think this
![odoo_error](https://cloud.githubusercontent.com/assets/252365/3909719/abb0b872-2310-11e4-85c7-b1075a65e6d6.JPG)

Also there is an updated version of gdata at 
https://gdata-python-client.googlecode.com/files/gdata-2.0.18.tar.gz

**Comment by jammins** [comment]
Hi, how did you change the password?its not working for my case.

**Comment by jammins** [comment]
vi /etc/odoo-server.conf
to open to edit mode
then move with the 'up''down' button to the place where that password is
so take ur cursor to that line
then go to the end of the line, i.e 'after superadminpassword'
cursor should be there
 when the cursor is there, click in leter 'i'
make sure its small 'i'
then press back space to rub the password and put
then press back space to rub the password and put the required password
once u have done that, click 'escape' key
then type the folowing
:wq!
just type, thy will show up at the bottom
 then press enter
 that saves the file and exits....
